version: '3'

volumes:
  postgres_data:


services:
  postgres:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=twitter_clone_auth
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

### This is used for local auth service development
